import React from 'react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { TrendingUp, Eye, Shield, Zap, BadgeCheck, Heart, Users, MapPin, Briefcase, Wallet, Headphones, Handshake } from 'lucide-react'
import ParticleCanvas from '../components/ParticleCanvas'
import SectionLabel from '../components/SectionLabel'

const fadeUp = {
  initial: { opacity: 0, y: 36 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: '-60px' },
  transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] }
}

const milestones = [
  { year: '2016', title: 'Founded in Bhilwara', desc: 'Established by Shri Mukesh Jain in Bhilwara, Rajasthan — built on one promise: no honest borrower turned away for paperwork.' },
  { year: '2017', title: 'RBI NBFC Licence', desc: 'Received RBI registration as a Non-Banking Financial Company (NBFC-ICC), registration number B-10.00264.' },
  { year: '2026', title: '₹200 Cr+ Disbursed', desc: 'Serving 1,800+ families across 3 branches in Rajasthan — Tier 2 Bharat deserves Tier 1 credit.' },
]

const teams = [
  {
    icon: <Briefcase size={22} />,
    title: 'Leadership',
    body: 'Founder Shri Mukesh Jain leads Arnav FinCorp with a hands-on style — every loan above the standard ticket is reviewed personally. The same person who approves your loan is the person you can sit across the desk from.',
  },
  {
    icon: <Wallet size={22} />,
    title: 'Credit & Risk',
    body: 'Our underwriting team is trained on cash-flow analysis, not CIBIL-only scoring. We look at the working shop, the standing crop, the bank passbook over six months — not at one number generated by a black-box model.',
  },
  {
    icon: <Handshake size={22} />,
    title: 'Field Operations',
    body: 'Field officers across our three Rajasthan branches — hired locally and fluent in Marwari and Mewari. They visit shops, farms and homes, often arriving before paperwork is even ready, and stay involved through repayment.',
  },
  {
    icon: <Headphones size={22} />,
    title: 'Customer Care',
    body: 'Named relationship managers, not call-centre queues. Reach us on WhatsApp at 88751-20888 or our branch landline 01482-238388 — Monday to Saturday, in your language, on a working number.',
  },
]

const values = [
  {
    icon: <Shield size={22} />,
    title: 'Transparency',
    body: 'No hidden charges, no fine print. Every term is read aloud in your language before you sign — because trust in a Tier 2 town travels faster than any ad campaign.',
  },
  {
    icon: <Zap size={22} />,
    title: 'Speed',
    body: '48-hour decisioning for ticket sizes up to ₹25 lakh. Our field officers visit your shop, your farm, your home — paperwork should not delay a harvest season or a wedding.',
  },
  {
    icon: <BadgeCheck size={22} />,
    title: 'Responsibility',
    body: 'RBI Registered NBFC committed to the Fair Practices Code. We lend only what you can repay — and we measure success by how many customers come back for their second loan.',
  },
  {
    icon: <Heart size={22} />,
    title: 'Bharat First',
    body: 'Built for the trader in Kota, the farmer in Sri Ganganagar, the boutique owner in Udaipur. We do not chase metro vanity — we serve the Bharat that built India.',
  },
  {
    icon: <Users size={22} />,
    title: 'Relationship Banking',
    body: 'Every customer is assigned a named relationship officer. No call centres, no IVR mazes. The person who approved your loan is the person you can call directly.',
  },
  {
    icon: <MapPin size={22} />,
    title: 'Rooted Local',
    body: 'Our branch managers are hired from within 50 km of each branch. They know the local mandi rates, the festival cycles, the genuine borrowers. Underwriting that machines cannot replicate.',
  },
]

const About = () => {
  const { t } = useTranslation()
  return (
    <div className="about-page">
      <ParticleCanvas />

      {/* ══ HERO ══ */}
      <section className="about-hero">
        <motion.div {...fadeUp}>
          <SectionLabel>{t('aboutPage.eyebrow')}</SectionLabel>
          <h1 className="about-hero-title">
            {t('aboutPage.titleStart')}{' '}
            <span className="italic-accent">{t('aboutPage.titleAccent')}</span>{' '}
            {t('aboutPage.titleEnd')}
          </h1>
          <p className="about-hero-sub">
            {t('aboutPage.subtitle')}
          </p>
        </motion.div>
      </section>

      {/* ══ BODY GRID ══ */}
      <div className="about-grid">

        {/* ── Founder Story Card ── */}
        <motion.div className="about-card" {...fadeUp} style={{ marginBottom: 24, maxWidth: 880, marginLeft: 'auto', marginRight: 'auto' }}>
          <div className="about-card-icon">
            <Heart size={22} />
          </div>
          <p className="about-card-eyebrow">Our Story</p>
          <h2 className="about-card-title">Founded in Bhilwara to serve the borrower no metro bank will see.</h2>
          <p className="about-card-body">
            Arnav FinCorp was founded in 2016 by Shri Mukesh Jain in Bhilwara, Rajasthan — a textile town where business is done
            on relationships, cash flow, and reputation, not on the spreadsheet a metro algorithm prefers. From a single office
            on Hari Seva Marg, we set out to serve the borrowers three nationalised banks had already turned away that month:
            traders with real income but no ITR, shop owners with steady custom but no salary slip, families with property but
            no CIBIL track record.
            <br /><br />
            In 2017 we received our RBI NBFC-ICC licence (registration number B-10.00264). In the nine years since, we have grown
            to three branches across Rajasthan, disbursed over ₹200 crore to more than 1,800 families, and built the kind of
            lender our customers actually come back to — for their second loan, their cousin's loan, their daughter's wedding loan.
            <br /><br />
            Our underwriting philosophy has not changed in nine years: <em>cash flow is real, character is verifiable, and a Tier 2
            borrower with a working shop is a better credit risk than any spreadsheet will tell you.</em>
          </p>
        </motion.div>

        {/* ── Our Teams (NEW) ── */}
        <motion.div {...fadeUp} style={{ marginTop: 40 }}>
          <div style={{ textAlign: 'center', marginBottom: 32 }}>
            <SectionLabel>Our Teams</SectionLabel>
            <h2 className="section-title" style={{ marginTop: 12, fontSize: 'clamp(1.5rem, 2.4vw, 2rem)' }}>The people behind every approval.</h2>
          </div>
          <div className="about-val-grid">
            {teams.map((tm) => (
              <div key={tm.title} className="about-card">
                <div className="about-card-icon">{tm.icon}</div>
                <h3 className="about-card-title" style={{ fontSize: '1.15rem' }}>{tm.title}</h3>
                <p className="about-card-body">{tm.body}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* ── Our Values (3 col) ── */}
        <motion.div {...fadeUp} style={{ marginTop: 48 }}>
          <div style={{ textAlign: 'center', marginBottom: 32 }}>
            <SectionLabel>Our Values</SectionLabel>
            <h2 className="section-title" style={{ marginTop: 12, fontSize: 'clamp(1.5rem, 2.4vw, 2rem)' }}>What we stand for</h2>
          </div>
          <div className="about-val-grid">
            {values.map((v) => (
              <div key={v.title} className="about-card">
                <div className="about-card-icon">{v.icon}</div>
                <h3 className="about-card-title" style={{ fontSize: '1.15rem' }}>{v.title}</h3>
                <p className="about-card-body">{v.body}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* ── Milestone Timeline ── */}
        <motion.div className="about-timeline" {...fadeUp}>
          <div className="about-timeline-header">
            <SectionLabel>Our Journey</SectionLabel>
            <h2 className="section-title" style={{ marginTop: 12, fontSize: 'clamp(1.5rem, 2.4vw, 2rem)' }}>9 years of trust, one milestone at a time.</h2>
          </div>
          <div className="about-timeline-track">
            {milestones.map((m) => (
              <div key={m.year} className="about-timeline-item">
                <div className="about-timeline-dot">
                  <div className="about-timeline-dot-inner" />
                </div>
                <span className="about-timeline-year">{m.year}</span>
                <span className="about-timeline-title">{m.title}</span>
                <span className="about-timeline-desc">{m.desc}</span>
              </div>
            ))}
          </div>
        </motion.div>

        {/* ── Mission + Vision (moved here, after Journey) ── */}
        <div className="about-mv-grid" style={{ marginTop: 16 }}>
          <motion.div className="about-card" {...fadeUp}>
            <div className="about-card-icon">
              <TrendingUp size={22} />
            </div>
            <p className="about-card-eyebrow">Mission</p>
            <h2 className="about-card-title">Credit that meets Bharat where it lives — in its mandis, its mohallas, its mandirs.</h2>
            <p className="about-card-body">
              To provide accessible, transparent and fair credit to the families and small businesses of Tier 2 and Tier 3
              India who have real income, real assets and real ambition — but no CIBIL track record. We underwrite
              cash-flow first, document second, and the human always at the centre.
            </p>
          </motion.div>

          <motion.div className="about-card" {...fadeUp} transition={{ delay: 0.1, duration: 0.8, ease: [0.16, 1, 0.3, 1] }}>
            <div className="about-card-icon">
              <Eye size={22} />
            </div>
            <p className="about-card-eyebrow">Vision</p>
            <h2 className="about-card-title">Rajasthan&apos;s most trusted Tier 2 NBFC — built in Bhilwara, growing across Bharat.</h2>
            <p className="about-card-body">
              To deepen our presence across Rajasthan and the neighbouring Tier 2 belt — proving that the future of
              Indian lending is not in Mumbai BKC or Bengaluru, but in the towns where India&apos;s real entrepreneurs
              live, work and dream.
            </p>
          </motion.div>
        </div>

        {/* ── CTA ── */}
        <motion.div className="about-cta" {...fadeUp}>
          <h2>{t('aboutPage.ctaTitle')}</h2>
          <p>{t('aboutPage.ctaDesc')}</p>
          <div className="about-cta-btns">
            <Link to="/contact" className="about-cta-btn-primary">{t('aboutPage.ctaPrimary')} →</Link>
            <Link to="/loans" className="about-cta-btn-secondary">{t('aboutPage.ctaSecondary')}</Link>
          </div>
        </motion.div>

      </div>{/* end about-grid */}
    </div>
  )
}

export default About
